"use client";

import { useState } from "react";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import { getOrderSummary } from "./actions";
import { type OrderSummaryOutput } from "@/ai/flows/order-summary-generation";
import { Sparkles, Loader2 } from "lucide-react";

type Order = {
  id: string;
  customer: string;
  vehicle: {
    make: string;
    model: string;
    year: number;
  };
  status: "Completed" | "In Progress" | "Pending";
  services: string;
  parts: string;
  total: number;
};

const mockOrders: Order[] = [
  {
    id: "ORD-001",
    customer: "John Doe",
    vehicle: { make: "Honda", model: "Civic", year: 2021 },
    status: "Completed",
    services: "Oil change, tire rotation",
    parts: "Oil filter, 5W-30 synthetic oil",
    total: 125.5,
  },
  {
    id: "ORD-002",
    customer: "Jane Smith",
    vehicle: { make: "Ford", model: "F-150", year: 2019 },
    status: "In Progress",
    services: "Brake pad replacement",
    parts: "Front ceramic brake pads",
    total: 350.0,
  },
  {
    id: "ORD-003",
    customer: "Sam Wilson",
    vehicle: { make: "Toyota", model: "Camry", year: 2022 },
    status: "Pending",
    services: "Diagnostic check",
    parts: "N/A",
    total: 75.0,
  },
  {
    id: "ORD-004",
    customer: "Emily Brown",
    vehicle: { make: "BMW", model: "X5", year: 2020 },
    status: "Completed",
    services: "Annual inspection, air filter replacement",
    parts: "Cabin air filter, engine air filter",
    total: 215.75,
  },
];

const statusVariant: { [key in Order["status"]]: "default" | "secondary" | "destructive" } = {
    Completed: "default",
    "In Progress": "secondary",
    Pending: "outline"
}


export default function OrdersPage() {
  const [isDialogOpen, setIsDialogOpen] = useState(false);
  const [summary, setSummary] = useState<OrderSummaryOutput | null>(null);
  const [isLoading, setIsLoading] = useState(false);

  const handleGenerateSummary = async (order: Order) => {
    setIsDialogOpen(true);
    setIsLoading(true);
    setSummary(null);

    const result = await getOrderSummary({
      servicesPerformed: order.services,
      partsReplaced: order.parts,
      totalCost: order.total,
      vehicleMake: order.vehicle.make,
      vehicleModel: order.vehicle.model,
      vehicleYear: order.vehicle.year,
    });

    if (result.data) {
      setSummary(result.data);
    }
    setIsLoading(false);
  };

  return (
    <div className="flex flex-col gap-8">
      <div>
        <h1 className="text-3xl font-bold font-headline tracking-tight">Service Orders</h1>
        <p className="text-muted-foreground">
          Manage and review all service orders.
        </p>
      </div>
      <div className="rounded-lg border">
        <Table>
          <TableHeader>
            <TableRow>
              <TableHead>Order ID</TableHead>
              <TableHead>Customer</TableHead>
              <TableHead>Vehicle</TableHead>
              <TableHead>Status</TableHead>
              <TableHead className="text-right">Total</TableHead>
              <TableHead className="text-right">Actions</TableHead>
            </TableRow>
          </TableHeader>
          <TableBody>
            {mockOrders.map((order) => (
              <TableRow key={order.id}>
                <TableCell className="font-medium">{order.id}</TableCell>
                <TableCell>{order.customer}</TableCell>
                <TableCell>{`${order.vehicle.year} ${order.vehicle.make} ${order.vehicle.model}`}</TableCell>
                <TableCell>
                  <Badge variant={statusVariant[order.status]}>{order.status}</Badge>
                </TableCell>
                <TableCell className="text-right">${order.total.toFixed(2)}</TableCell>
                <TableCell className="text-right">
                  <Button
                    variant="ghost"
                    size="sm"
                    onClick={() => handleGenerateSummary(order)}
                  >
                    Generate Summary
                    <Sparkles className="ml-2 h-4 w-4" />
                  </Button>
                </TableCell>
              </TableRow>
            ))}
          </TableBody>
        </Table>
      </div>

      <Dialog open={isDialogOpen} onOpenChange={setIsDialogOpen}>
        <DialogContent>
          <DialogHeader>
            <DialogTitle>AI-Generated Order Summary</DialogTitle>
            <DialogDescription>
              This is a concise summary of the service order generated by AI.
            </DialogDescription>
          </DialogHeader>
          <div className="py-4">
            {isLoading && (
              <div className="flex items-center justify-center gap-2 text-muted-foreground">
                <Loader2 className="h-5 w-5 animate-spin" />
                <span>Generating summary...</span>
              </div>
            )}
            {summary && <p className="text-sm">{summary.summary}</p>}
          </div>
        </DialogContent>
      </Dialog>
    </div>
  );
}
